SERVER_TRANSPORT="streamable-http"

FASTMCP_LOG_LEVEL="INFO"
FASTMCP_AUTH__ISSUER_URL="http://127.0.0.1:9000"
FASTMCP_AUTH__RESOURCE_SERVER_URL="http://127.0.0.1:8000/mcp"
FASTMCP_AUTH__REQUIRED_SCOPES='["https://www.googleapis.com/auth/adwords"]'


GOOGLE_ADS_CLIENT_ID=1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
GOOGLE_ADS_CLIENT_SECRET=ABCDefGHIJKLMNopqrstuvwx
GOOGLE_ADS_DEVELOPER_TOKEN=G9aiSN7uBB0TBhA8doPoNg
